version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y ssh-client
      - aws s3 cp s3://cryptex-credentials/github/github.pk /root/.ssh/github
      - chmod 600 /root/.ssh/github
      - ssh-keyscan -H github.com > /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/known_hosts
      - chown root:root /root/.ssh/known_hosts
      - aws s3 cp s3://cryptex-credentials/github/ssh-config.txt /root/.ssh/config
      - chmod 600 /root/.ssh/config
      - chown root:root /root/.ssh/config
      - npm install -g npm@5.7.1
  prebuild:
    commands:
      - aws s3 cp s3://cryptex-credentials/neural-net/test/config.json config.json
  build:
    commands:
      - npm ci
      - npm run compile
      - npm test